import {
  SeasonGoal,
  Mesocycle,
  Microcycle,
} from '../types/planning';

export const INITIAL_PLANNING_SEED: {
  season: SeasonGoal;
  mesocycles: Mesocycle[];
  microcycles: Microcycle[];
} = {
  season: {
    id: 'season-2025-2026-senior',
    temporada: '2025-2026',
    categoria: 'Senior',
    objetivoPrincipal: 'Ascenso a Primera División Nacional y consolidación del modelo de juego colectivo.',
    objetivosDeportivos: [
      'Finalizar la temporada regular entre los 2 primeros puestos del grupo.',
      'Clasificar y competir en la Final Four de ascenso.',
      'Mantener un diferencial de puntos positivo superior a +8.5 por partido.',
    ],
    objetivosFormativos: [
      'Desarrollar la autonomía y lectura táctica en toma de decisiones en <2 segundos.',
      'Establecer cultura de equipo basada en alta intensidad defensiva y comunicación verbal constante.',
      'Mejorar el porcentaje colectivo de tiro exterior y tiro libre bajo fatiga.',
    ],
    estiloDeJuego: 'Transición rápida ofensiva tras rebote defensivo, juego dinámico de 5 abiertos con penetrar y doblar (drive & kick), y defensa presionante a 3/4 de campo.',
    fechaInicio: '2025-09-01',
    fechaFin: '2026-06-15',
    createdAt: '2025-09-01T08:00:00.000Z',
  },
  mesocycles: [
    {
      id: 'meso-1-pretemporada',
      seasonGoalId: 'season-2025-2026-senior',
      numero: 1,
      nombre: 'Mesociclo 1: Pretemporada y Construcción del Sistema',
      fechaInicio: '2025-09-01',
      fechaFin: '2025-09-28',
      objetivoPrincipal: 'Puesta a punto física, fijación de reglas defensivas y establecimiento del espaciado ofensivo básico.',
      estado: 'activo',
      resumenCierre: 'Mesociclo enfocado en volumen de juego colectivo. Excelente acoplamiento táctico pero con déficit acumulado en fundamentos de tiro y técnica individual.',
      goals: [
        {
          id: 'goal-meso-1-tact-1',
          mesocycleId: 'meso-1-pretemporada',
          area: 'tactica',
          descripcion: 'Consolidar el spacing ofensivo (5 Abiertos) y las lecturas de Pick & Roll central con pase al lado débil.',
          indicadorExito: 'Más del 70% de lecturas ofensivas correctas en situaciones reales de 5v5.',
          estado: 'cumplido',
        },
        {
          id: 'goal-meso-1-tact-2',
          mesocycleId: 'meso-1-pretemporada',
          area: 'tactica',
          descripcion: 'Estructurar el balance defensivo y las rotaciones de ayuda en primera línea.',
          indicadorExito: 'Menos de 8 puntos concedidos en contraataque rival por partido amistoso.',
          estado: 'cumplido',
        },
        {
          id: 'goal-meso-1-tec-1',
          mesocycleId: 'meso-1-pretemporada',
          area: 'tecnica',
          descripcion: 'Mecánica y velocidad de armado de tiro tras recepción (Catch & Shoot en menos de 1.2s).',
          indicadorExito: 'Porcentaje superior al 45% en series de tiro exterior tras movimiento.',
          estado: 'no_cumplido',
        },
      ],
    },
    {
      id: 'meso-2-competicion-fase1',
      seasonGoalId: 'season-2025-2026-senior',
      numero: 2,
      nombre: 'Mesociclo 2: Competición Regular - Fase 1',
      fechaInicio: '2025-09-29',
      fechaFin: '2025-10-26',
      objetivoPrincipal: 'Optimizar la eficacia ofensiva ante defensas zonales y afinar detalles tácticos de scout.',
      estado: 'planificado',
      goals: [
        {
          id: 'goal-meso-2-tec-1',
          mesocycleId: 'meso-2-competicion-fase1',
          area: 'tecnica',
          descripcion: 'Finalizaciones en contacto y tiro flotante tras penetración de exteriores.',
          indicadorExito: '>55% de acierto en penetraciones al aro.',
          estado: 'pendiente',
        },
        {
          id: 'goal-meso-2-tact-1',
          mesocycleId: 'meso-2-competicion-fase1',
          area: 'tactica',
          descripcion: 'Ataque contra defensas en zona 2-3 y 1-3-1 con sobrecarga de esquina.',
          indicadorExito: 'Generar tiros liberados en >60% de posesiones ante zona.',
          estado: 'pendiente',
        },
        {
          id: 'goal-meso-2-fis-1',
          mesocycleId: 'meso-2-competicion-fase1',
          area: 'fisica',
          descripcion: 'Mantenimiento de potencia anaeróbica y agilidad lateral reactiva.',
          indicadorExito: 'Mantener tiempo de test de agilidad por debajo de 11.2s.',
          estado: 'pendiente',
        },
        {
          id: 'goal-meso-2-men-1',
          mesocycleId: 'meso-2-competicion-fase1',
          area: 'mental',
          descripcion: 'Gestión de momentos clave y control de faltas en los últimos 3 minutos de partido.',
          indicadorExito: 'Efectividad >80% en posesiones de crunch time.',
          estado: 'pendiente',
        },
      ],
    },
  ],
  microcycles: [
    {
      id: 'micro-1-semana-1',
      mesocycleId: 'meso-1-pretemporada',
      semana: 1,
      fechaInicio: '2025-09-01',
      fechaFin: '2025-09-07',
      objetivoSemanal: 'Introducción de normas de juego y activación aeróbica.',
      cargasPlanificadas: { sesiones: 4, intensidad: 'Media', volumenMinutos: 360 },
      goalIds: ['goal-meso-1-tact-1', 'goal-meso-1-tec-1'],
      estado: 'cerrado',
      sessions: [
        {
          id: 'sess-1-1',
          microcycleId: 'micro-1-semana-1',
          fecha: '2025-09-01',
          titulo: 'Sesión 1: Espaciado inicial y acondicionamiento',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Movilidad articular y carrera continua variable', duracionMin: 20 },
            { area: 'tecnica', contenido: 'Manejo de balón a 2 manos y pases en parejas', duracionMin: 20 },
            { area: 'tactica', contenido: 'Spacing 5 Abiertos y reglas de pase y corte', duracionMin: 50 },
          ],
        },
        {
          id: 'sess-1-2',
          microcycleId: 'micro-1-semana-1',
          fecha: '2025-09-03',
          titulo: 'Sesión 2: Balance defensivo y cortes',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Fuerza con peso corporal y pliometría baja', duracionMin: 20 },
            { area: 'tecnica', contenido: 'Paradas en 1 y 2 tiempos encarando el aro', duracionMin: 15 },
            { area: 'tactica', contenido: 'Rotaciones de balance defensivo 3c2 y 5c5', duracionMin: 55 },
          ],
        },
        {
          id: 'sess-1-3',
          microcycleId: 'micro-1-semana-1',
          fecha: '2025-09-05',
          titulo: 'Sesión 3: Continuaciones de Pick & Roll',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Velocidad de reacción con conos', duracionMin: 15 },
            { area: 'tecnica', contenido: 'Tiro tras pase de pecho', duracionMin: 15 },
            { area: 'tactica', contenido: 'Sistemas 1 y 2 con bloqueo directo central', duracionMin: 60 },
          ],
        },
        {
          id: 'sess-1-4',
          microcycleId: 'micro-1-semana-1',
          fecha: '2025-09-06',
          titulo: 'Sesión 4: Partido de entrenamiento interno',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Calentamiento dinámico activo', duracionMin: 15 },
            { area: 'tecnica', contenido: 'Rueda de tiro analítico de calentamiento', duracionMin: 10 },
            { area: 'tactica', contenido: '5v5 Real aplicando normas ofensivas y defensivas', duracionMin: 65 },
          ],
        },
      ],
      evaluation: {
        id: 'eval-micro-1',
        microcycleId: 'micro-1-semana-1',
        fecha: '2025-09-07',
        objetivosCumplidos: ['goal-meso-1-tact-1'],
        objetivosNoCumplidos: [],
        comentarioLibre: 'Buena asimilación inicial del spacing.',
        percepcionEntrenador: 4,
      },
    },
    {
      id: 'micro-2-semana-2',
      mesocycleId: 'meso-1-pretemporada',
      semana: 2,
      fechaInicio: '2025-09-08',
      fechaFin: '2025-09-14',
      objetivoSemanal: 'Profundización en variantes tácticas de Pick & Roll y balance.',
      cargasPlanificadas: { sesiones: 4, intensidad: 'Alta', volumenMinutos: 360 },
      goalIds: ['goal-meso-1-tact-1', 'goal-meso-1-tact-2', 'goal-meso-1-tec-1'],
      estado: 'cerrado',
      sessions: [
        {
          id: 'sess-2-1',
          microcycleId: 'micro-2-semana-2',
          fecha: '2025-09-08',
          titulo: 'Sesión 5: Lectura defensiva de Pick & Roll',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Aceleraciones y frenadas en pista', duracionMin: 20 },
            { area: 'tecnica', contenido: 'Pase picado con mano no dominante', duracionMin: 10 },
            { area: 'tactica', contenido: 'Ataque contra Show/Flash y Drop en PnR', duracionMin: 60 },
          ],
        },
        {
          id: 'sess-2-2',
          microcycleId: 'micro-2-semana-2',
          fecha: '2025-09-10',
          titulo: 'Sesión 6: Balances y ayudas del lado débil',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Circuitos de fuerza funcional', duracionMin: 20 },
            { area: 'tecnica', contenido: 'Tiro tras bote de salida', duracionMin: 10 },
            { area: 'tactica', contenido: 'Rotaciones de ayuda y recuperación (Closeout)', duracionMin: 60 },
          ],
        },
        {
          id: 'sess-2-3',
          microcycleId: 'micro-2-semana-2',
          fecha: '2025-09-12',
          titulo: 'Sesión 7: Automatización de salidas de presión',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Desplazamientos defensivos a campo entero', duracionMin: 15 },
            { area: 'tecnica', contenido: 'Cambios de dirección entre conos', duracionMin: 10 },
            { area: 'tactica', contenido: 'Ruptura de presión 2-2-1 y 1-2-1-1', duracionMin: 65 },
          ],
        },
        {
          id: 'sess-2-4',
          microcycleId: 'micro-2-semana-2',
          fecha: '2025-09-13',
          titulo: 'Sesión 8: 5c5 Condicionado',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Activación con balón medicinal', duracionMin: 15 },
            { area: 'tecnica', contenido: 'Mecánica de tiro libre', duracionMin: 5 },
            { area: 'tactica', contenido: '5v5 con límite de 4 pases y tiros en ventaja', duracionMin: 70 },
          ],
        },
      ],
      evaluation: {
        id: 'eval-micro-2',
        microcycleId: 'micro-2-semana-2',
        fecha: '2025-09-14',
        objetivosCumplidos: ['goal-meso-1-tact-2'],
        objetivosNoCumplidos: [],
        comentarioLibre: 'Gran nivel de intensidad táctica.',
        percepcionEntrenador: 4,
      },
    },
    {
      id: 'micro-3-semana-3',
      mesocycleId: 'meso-1-pretemporada',
      semana: 3,
      fechaInicio: '2025-09-15',
      fechaFin: '2025-09-21',
      objetivoSemanal: 'Ajustes finales de pretemporada y preparación para partido amistoso.',
      cargasPlanificadas: { sesiones: 4, intensidad: 'Alta', volumenMinutos: 360 },
      goalIds: ['goal-meso-1-tact-1', 'goal-meso-1-tact-2', 'goal-meso-1-tec-1'],
      estado: 'activo',
      sessions: [
        {
          id: 'sess-3-1',
          microcycleId: 'micro-3-semana-3',
          fecha: '2025-09-15',
          titulo: 'Sesión 9: Sistemas especiales de saque de fondo y banda',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Potencia de salto y arrancadas cortas', duracionMin: 18 },
            { area: 'tecnica', contenido: 'Recepción encarando aro', duracionMin: 5 },
            { area: 'tactica', contenido: 'Jugadas de fondo (BLOB) y banda (SLOB)', duracionMin: 67 },
          ],
        },
        {
          id: 'sess-3-2',
          microcycleId: 'micro-3-semana-3',
          fecha: '2025-09-17',
          titulo: 'Sesión 10: Situaciones de partido y control de ritmo',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Intervalos aeróbicos de alta intensidad', duracionMin: 18 },
            { area: 'tecnica', contenido: 'Pase a una mano en bote', duracionMin: 5 },
            { area: 'tactica', contenido: '5v5 Simulando ventajas de +4 y -4 en 2 minutos', duracionMin: 67 },
          ],
        },
        {
          id: 'sess-3-3',
          microcycleId: 'micro-3-semana-3',
          fecha: '2025-09-19',
          titulo: 'Sesión 11: Repaso general del sistema',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Velocidad y agilidad', duracionMin: 18 },
            { area: 'tecnica', contenido: 'Tiro por parejas', duracionMin: 5 },
            { area: 'tactica', contenido: '5v5 a campo entero con scout rival', duracionMin: 67 },
          ],
        },
        {
          id: 'sess-3-4',
          microcycleId: 'micro-3-semana-3',
          fecha: '2025-09-20',
          titulo: 'Sesión 12: Tiro previo y puesta a punto de partido',
          duracionMin: 90,
          contenidos: [
            { area: 'fisica', contenido: 'Activación neuro-muscular rápida', duracionMin: 15 },
            { area: 'tecnica', contenido: 'Series de tiro estático', duracionMin: 5 },
            { area: 'tactica', contenido: 'Repaso 5v0 de opciones tácticas ofensivas', duracionMin: 70 },
          ],
        },
      ],
      evaluation: {
        id: 'eval-micro-3',
        microcycleId: 'micro-3-semana-3',
        fecha: '2025-09-21',
        objetivosCumplidos: ['goal-meso-1-tact-1', 'goal-meso-1-tact-2'],
        objetivosNoCumplidos: ['goal-meso-1-tec-1'],
        comentarioLibre: 'En el partido fallamos muchos tiros liberados y finalizaciones cómodas. La táctica funcionó para generar tiros abiertos, pero la ejecución técnica individual no estuvo al nivel.',
        percepcionEntrenador: 3,
        incidencias: ['Bajo porcentaje en tiros abiertos de 3 puntos (4/22)', 'Pérdidas no forzadas en pases de finalización'],
      },
    },
    {
      id: 'micro-4-semana-4',
      mesocycleId: 'meso-1-pretemporada',
      semana: 4,
      fechaInicio: '2025-09-22',
      fechaFin: '2025-09-28',
      objetivoSemanal: 'Refuerzo técnico de tiro y finalizaciones + cierre de pretemporada.',
      cargasPlanificadas: { sesiones: 4, intensidad: 'Media', volumenMinutos: 360 },
      goalIds: ['goal-meso-1-tec-1', 'goal-meso-1-tact-1'],
      estado: 'planificado',
      sessions: [],
    },
  ],
};
